name: Conan Build and Upload
on:
  repository_dispatch:
    types: [conan]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install conan
    - name: Run Conan Create
      run: |
        conan config install https://github.com/aivero/conan-config.git
        conan create . aivero/stable